name: CI - Halmos

on:
  push:
    branches: ["**"]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: ["**"]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  run-halmos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install halmos
        run: python3 -m pip install --upgrade halmos
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Run halmos
        run: |
          halmos --contract NapoliInvariants